title: Investment Analyst (Venture Capital)
author: Edwardykk
email: yungkeenking@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  An investment analyst covering Series A onwards technology investment
  in Southeast Asia. Deals covered include fintech, IOT, e-commerce,
  logistics & artificial intelligence.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
